### ISSUE TITLE
Can I use multiple BME280s with this code?

### ISSUE THREAD

**Issue by Hojae** [embeddedadventures/BME280#2]
I'm using the breakout board of BME280, MOD-1022, but I'm wondering how I can use multiple sensors with this code.
Is there anyone who tried having multiple MOD-1022s on the same board?

Thanks,

**Comment by Kabron287** [comment]
In BME280_MOD-1022.h
Comment:
//#define addrBME280        0x76
and add:
extern int addrBME280;

In your sketch use
int addrBME280=0x76;      // or 0x77;
you can change it during execution

Also you can powerup each couple of BME280(one 0x76, another 0x77) via separate ESP8266 pin. So, you'll have several branches which can be switched alternatively.

**Comment by Eheran1** [comment]
Would this result in only one set of correction parameters beeing used or do both chips use their own set of calibration data?

**Comment by Kabron287** [comment]
You need two sets.
