### ISSUE TITLE
Your Library Works Great! One question.

### ISSUE THREAD

**Issue by waltb01** [embeddedadventures/BME280#7]
Thank you!! Working with no effort. My wiring is I2C with level convertor. Using sensors from Aliexpress.  However, any idea why when running the Adafruit BME280_test Library all I ever receive is "sensor not found"? Doesn't make any sense. Thanks.

**Comment by waltb01** [comment]
Answered my own question. The Adafruit BME280 library uses a different sensor address. The Bosch BME280 required the following line in their sketch: 
#define Addr 0x76

**Comment by iharris** [comment]
Great stuff! Thanks for the feedback.

cheers
Ian.
