### ISSUE TITLE
Works perfect with Due, except with the latest IDE 1.8.2, an include was needed

### ISSUE THREAD

**Issue by frostybeard** [embeddedadventures/BME280#9]
I am using a BME280 (MOD-1022) with Due. At first the example would not compile, but after browsing around a while, I found I needed this include that I put into a pull request for your convenience.
After that was added, it works as-is with Due.
Great product. Now I will add my MOD-1016 lightning sensor.

Here's the pull request:
https://github.com/embeddedadventures/BME280/pull/8

**Comment by dr4nc3s** [comment]
Thanks!
